<a href="https://colab.research.google.com/github/19PA1A0236/AI-lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXPERIMENT-1 1.NUMPY 
#i)Different ways to create numpy arrays
##a)Create a numpy array using list



In [ ]:
import numpy as np
a = np.array([2,6,9])  
print (a)

[2 6 9]


In [ ]:
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


ii).Add,remove,modify elements in an array.



In [ ]:
newArray = np.append(a,[44,36,48])
print(newArray)

[ 1  2  3  4 44 36 48]


In [ ]:
import numpy as np
l=np.array([4,6,9,3,7])
l=np.delete(l,4)
print(l)

[4 6 9 3]


In [ ]:
b=np.array([9,6,4,1,8,5])
b[b<2]=-1
print(b)

[ 9  6  4 -1  8  5]


iii).Arthimetic operations on Numpy array


In [ ]:
import numpy as np
v=np.random.random((8,8))
n=np.random.random((8,8))
sum=np.add(v,n)
diff=np.subtract(v,n)
prod=np.multiply(v,n)
quo=np.divide(v,n)
mod=np.mod(v,n)
pow=np.power(v,n)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.23398146 0.40253284 1.03703056 0.05134812 0.40995854 1.26197622
  1.7435294  0.82405167]
 [0.51781404 0.87663604 0.45559698 1.71394472 1.02478364 1.37719553
  0.64912631 0.97235899]
 [0.18425138 1.4491573  0.49822159 1.64362328 0.69283911 0.48945569
  0.99826158 1.41102499]
 [0.714708   0.78224007 1.43802912 0.47947344 1.19353961 0.61511211
  0.54241572 0.63432066]
 [0.66318959 1.67975527 1.32792062 1.48717493 0.98703004 0.87566163
  1.67739121 1.11373843]
 [0.35116757 0.55841289 1.52027418 1.0060255  0.85558969 0.16596659
  1.08890513 1.62514533]
 [0.25490471 1.16358829 1.93979122 0.61559141 1.3863378  0.28793542
  1.02123979 0.8365854 ]
 [1.06783833 1.04969542 0.96438106 1.26918863 1.07922916 1.02123825
  1.35284823 0.80935267]]
[[ 0.63594816  0.1947187   0.92616619 -0.05133487 -0.16548487 -0.57808451
  -0.23186527 -0.71760914]
 [-0.22373091 -0.75881548  0.06045962  0.03496101 -0.1455665   0.51721067
   0.55872127 -0.62501897]
 [-0.15977834 -0.30668276 -0.30064411  0.34287453  0.

iv).Slicing and iterating of numpy arrays


Slicing

In [ ]:
import numpy as np
arr=np.array([4,5,6,8,9,7])
print(arr[2:6])

[6 8 9 7]


Iterating

In [ ]:
for i in arr:
  print(i)

4
5
6
8
9
7


v)
.Matrix operation on numpy arrays.

In [ ]:
import numpy as np
v=np.array([[5,9],[4,3]])
i=np.array([[2,16],[1,12]])
print(np.add(v,i))
print(np.subtract(v,i))
print(np.divide(v,i))

[[ 7 25]
 [ 5 15]]
[[ 3 -7]
 [ 3 -9]]
[[2.5    0.5625]
 [4.     0.25  ]]
